# -*- coding: utf-8 -*-
from ztec.zdb import DB
db=DB()
db.load=True
db('confirmacion').campo('nombres',db.str,False,False,False)
db('confirmacion').campo('appelidos',db.str,False,False,False)
db('confirmacion').campo('correo',db.email,True,False,False)
db('confirmacion').campo('password',db.str,False,False,False)
db('confirmacion').campo('codigo',db.str,False,False,False)
db('usuarios').campo('nombres',db.str,False,False,False)
db('usuarios').campo('appelidos',db.str,False,False,False)
db('usuarios').campo('correo',db.email,True,False,False)
db('usuarios').campo('password',db.str,False,False,False)
db('usuarios').campo('foto',db.url,False,True,False)
db('usuarios').campo('imgs',db.list,False,True,False)
db('usuarios').campo('token',db.str,False,True,False)
db('usuarios').campo('login',db.bool,False,False,False)
db('msj_chat').campo('emisor',db.object,False,True,False)
db('msj_chat').campo('receptores',db.list,False,True,False)
db('msj_chat').campo('mensaje',db.str,False,True,False)
db('msj_chat').campo('hora',db.time,False,True,False)
db('msj_correo').campo('emisor',db.object,False,True,False)
db('msj_correo').campo('receptores',db.list,False,True,False)
db('msj_correo').campo('mensaje',db.str,False,True,False)
db('msj_correo').campo('hora',db.time,False,True,False)
db('apps').campo('nombre',db.str,False,True,False)
db('apps').campo('autores',db.list,False,True,False)
db('apps').campo('organizaciones',db.list,False,True,False)
db('apps').campo('versión',db.float,False,True,False)
db('apps').campo('estabilidad',db.str,False,True,False)
db('apps').campo('alias',db.str,False,True,False)
db('apps').campo('parentProjects',db.list,False,True,False)
db('apps').campo('technologyLevel',db.str,False,True,False)
db('apps').campo('icono',db.url,False,True,False)
db('apps').campo('web',db.url,False,True,False)
db('apps').campo('licencia',db.str,False,True,False)
db('posts').campo('publisher',db.object,False,True,False)
db('posts').campo('destinatarios',db.list,False,True,False)
db('posts').campo('img',db.url,False,True,False)
db('posts').campo('lectores',db.list,False,True,False)
db('posts').campo('interacciones',db.list,False,True,False)
db('posts').campo('comentarios',db.list,False,True,False)
db('tokens').campo('usuario',db.email,True,True,False)
db('tokens').campo('valor',db.str,True,True,False)
db('tokens').campo('emisión',db.datetime,False,True,False)
db('tokens').campo('expiración',db.datetime,False,True,False)
db('documentos').campo('app',db.str,False,True,True)
db('documentos').campo('libro',db.str,False,True,True)
db('documentos').campo('tema',db.str,False,True,True)
db('documentos').campo('texto',db.str,False,True,True)
db('libros').campo('nombre',db.str,False,True,True)
db('libros').campo('autores',db.list,False,True,True)
db('libros').campo('colaboradores',db.list,False,True,True)
db('libros').campo('referencias',db.list,False,True,True)
db('libros').campo('Editorial',db.str,False,True,True)
db('libros').campo('fecha de publicación',db.datetime,False,True,True)
db('libros').campo('web',db.url,False,True,True)
db('usuarios').insertar('jesus', 'zerpa', 'jesus26abraham1996@gmail.com', '1234', None, None, 's.GMFCo~', False)
db('tokens').insertar('jesus26abraham1996@gmail.com', 's.GMFCo~', '2017-01-02 13:21:28.238951', '2017-01-30 13:21:28.239063')
db('tokens').relacionar(0,'usuario',id= 0,tabla= 'usuarios',campo= 'correo',)
db('usuarios').relacionar(0,'token',id= 0,tabla= 'tokens',campo= 'valor',)
db.load=True
db.load=False
