from ztec.zdb import DB
db=DB()
db('usuarios').campo('nombres',db.str,False)
db('usuarios').campo('appelidos',db.str,False)
db('usuarios').campo('correo',db.email,True)
db('usuarios').campo('password',db.str,False)
db('usuarios').campo('foto',db.url,False)
db('usuarios').campo('imgs',db.list,False)
db('usuarios').campo('token',db.str,True)
db('msj_chat').campo('emisor',db.object,False)
db('msj_chat').campo('receptores',db.list,False)
db('msj_chat').campo('mensaje',db.str,False)
db('msj_chat').campo('hora',db.time,False)
db('msj_correo').campo('emisor',db.object,False)
db('msj_correo').campo('receptores',db.list,False)
db('msj_correo').campo('mensaje',db.str,False)
db('msj_correo').campo('hora',db.time,False)
db('apps').campo('nombre',db.str,False)
db('apps').campo('autores',db.list,False)
db('apps').campo('organizaciones',db.list,False)
db('apps').campo('versión',db.float,False)
db('apps').campo('estabilidad',db.str,False)
db('apps').campo('alias',db.str,False)
db('apps').campo('parentProjects',db.list,False)
db('apps').campo('technologyLevel',db.str,False)
db('apps').campo('icono',db.url,False)
db('apps').campo('web',db.url,False)
db('apps').campo('licencia',db.str,False)
db('posts').campo('publisher',db.object,False)
db('posts').campo('destinatarios',db.list,False)
db('posts').campo('img',db.url,False)
db('posts').campo('lectores',db.list,False)
db('posts').campo('interacciones',db.list,False)
db('posts').campo('comentarios',db.list,False)
db('tokens').campo('usuario',db.email,True)
db('tokens').campo('valor',db.str,True)
db('tokens').campo('emisión',db.datetime,False)
db('tokens').campo('expiración',db.datetime,False)
db('documentación').campo('app',db.str,False)
db('documentación').campo('libro',db.str,False)
db('documentación').campo('tema',db.str,False)
db('documentación').campo('texto',db.str,False)
db('admin').campo('nombre',db.str,False)
db('usuarios').insertar('jesus', 'zerpa', 'jesus26abraham1996@hotmail.com', '12345', 'https://localhost/AsenZor/apps/default/user/../../static/imgs/icono_perfil.jpg', [], '\x91\xbf\xc3\x8f\xc3<a\xc3')
db('tokens').insertar('jesus26abraham1996@hotmail.com', '\x91\xbf\xc3\x8f\xc3<a\xc3', '2016-12-27 13:06:28.330585', '2017-01-24 13:06:28.330632')
db('tokens').relacionar(0,'usuario',tabla= 'usuarios',id= 0,campo= 'correo',)
db('usuarios').relacionar(0,'token',tabla= 'tokens',id= 0,campo= 'valor',)
db('usuarios').insertar('jesus', 'zerpa', 'jesus26abraham1996@gmail.com', '12345', 'https://localhost/AsenZor/apps/default/user/../../static/imgs/icono_perfil.jpg', [], '\x82D\xc3\xb3=\xc2\xa2\xc3')
db('tokens').insertar('jesus26abraham1996@gmail.com', '\x82D\xc3\xb3=\xc2\xa2\xc3', '2016-12-27 13:07:25.485864', '2017-01-24 13:07:25.485912')
db('tokens').relacionar(1,'usuario',id= 1,tabla= 'usuarios',campo= 'correo',)
db('usuarios').relacionar(1,'token',id= 1,tabla= 'tokens',campo= 'valor',)
