#!/usr/bin/python
proyectos=["default","ej"]#lista de proyectos en el framework
proyectos_disp=["ej","default"]#lista de proyectos habilitados
host="https://localhost/"
fmk_dir="zerpatec"
fmk_url=fmk_dir+"/"
base_url=host+fmk_url
apps=["default"]
libs_folder="modulos/"
libs=["ztec"]#librerias cargadas en el framework
mod_debug=False;
apps_dir="apps"
apps_url=apps_dir+"/"
projects_dir="projects"
projects_url="projects/"
vistas_dir="vistas"
vistas_url=vistas_dir+"/"
logs=base_url+"log.txt"
lengs=["es","en"]
leng_default=["es"]

base_root="/opt/lampp/htdocs/"+fmk_url
default_app="default"
default_controller="default.py"
controles_dir="controles"
controller_url=controles_dir+"/"+default_controller
lanzador_dir="controles"
lanzador_default="lanzador.py"
lanzador_url=lanzador_dir+"/"+lanzador_default
templates_url="templates/"
vistas=["default"]#lista de todos la vistas html sin codigo python embebido
templates=[]#lista de todos los templates (vistas con codigo python embebido y widgets)
widgets=[]#lista con todos los widgets(templates minimalistas)
vistas_disp=["default"]#lista con las vistas disponibles para mostrar
templates_disp=[]#lista con los templates disponibles para mostrar
widgets_disp=[]#lista con los widgets disponibles para mostrar
custom_url=None
proyecto="default"#proyecto actual
error=False
controler_vista="vista.py"
main_libs_url=base_root+libs_folder
main_libs_url_relative="../"+libs_folder
consola=True