# -*- coding: utf-8 -*-
from ztec.zdb import DB
db=DB()
db.load=True
db('users').campo('username',db.str,False,True,False)
db('users').campo('password',db.str,False,True,False)
db('users').campo('email',db.email,True,True,False)
db('users').campo('name',db.str,False,True,False)
db('users').campo('lastname',db.str,False,True,False)
db('users').campo('register_date',db.datetime,False,True,False)
db('users').campo('rank',db.int,False,True,False)
db('users').campo('avatar',db.url,False,True,False)
db('users').campo('departament_id',db.int,False,True,False)
db('users').campo('position_id',db.int,False,True,False)
db('users').campo('total_hours',db.datetime,False,True,False)
db('positions').campo('name',db.str,False,True,False)
db('users').campo('id_department',db.int,False,True,False)
db('department').campo('name',db.str,False,True,False)
db('chronometers').campo('start_date',db.datetime,False,True,False)
db('chronometers').campo('end_date',db.datetime,False,True,False)
db('chronometers').campo('total_hours',db.datetime,False,True,False)
db('chronometers').campo('text',db.str,False,True,False)
db('chronometers').campo('id_user',db.int,False,True,False)
db('chronometers').campo('status',db.bool,False,True,False)
db('chronometers').campo('type',db.int,False,True,False)
db('user_projects').campo('user_id',db.int,False,True,False)
db('user_projects').campo('project_id',db.int,False,True,False)
db('projects').campo('name',db.str,False,True,False)
db('projects').campo('description',db.str,False,True,False)
db('projects').campo('start_date',db.datetime,False,True,False)
db('projects').campo('end_date',db.datetime,False,True,False)
db('projects').campo('status',db.bool,False,True,False)
db('users').insertar('jesus', '1242352352', 'jzerpa.pamax@gmail.com', 'jesus', 'zerpa', '2017-01-12 13:39:21.894223', 1, 'https://{{print config.base_url}}zerpatec/apps/pamaxWork/user/static/img/boy.png', 1, 1, '2017-01-12 13:39:22.096237')
db.load=True
db.load=False
